FROM python:3.10-slim

# Install Chromium
RUN apt-get update && apt-get install -y chromium

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Run the application
CMD ["python", "Sites.py"]